# Generated by Django 4.2.1 on 2024-01-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0005_alter_costcenterallocation_fy_and_more"),
        ("users", "0006_alter_bftuser_default_cc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bftuser",
            name="default_fc",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="costcenter.fundcenter",
                verbose_name="Default FC",
            ),
        ),
    ]
