# Generated by Django 4.2.1 on 2024-01-08 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_bftuser_default_fc"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bftuser",
            options={
                "permissions": (
                    ("create_data", "can create data"),
                    ("upload_data", "can upload data"),
                )
            },
        ),
    ]
