# Generated by Django 4.2.1 on 2023-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charges", "0002_costcenterchargeimport_fy"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCenterChargeMonthly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund", models.CharField(max_length=4)),
                ("costcenter", models.CharField(max_length=6)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("period", models.CharField(max_length=2)),
                (
                    "fy",
                    models.PositiveSmallIntegerField(
                        default="2023", verbose_name="Fiscal Year"
                    ),
                ),
            ],
        ),
    ]
