site_name: Business Forecasting Tool Documentation
docs_dir: 'mkdocs'
site_dir: 'htmldocs/static/mkdocs_build'
site_url: https://exemple.com
extra_css:
    - stylesheets/extra.css
nav:
    - Home: docs/index.md
    - About: docs/about.md
    - Line Items: docs/line-items-table.md
    - System administration: docs/system-administration/index.md
    - Uploading Line Items: docs/system-administration/uploading-line-items.md
    - Allocation: docs/allocation/index.md
    - Cost Center: docs/costcenter/index.md
    - Forecast Adjustment : docs/forecast-adjustment/index.md
    - Funds: docs/fund/index.md
    - Sources: docs/source/index.md
theme:
    name: material
    logo: docs/images/logo.png
    custom_dir: mkdocs/overrides
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.sections
        - search.highlight
        - search.suggest
        - header.autohide
    palette:
        primary: blue grey
        scheme: slate
        accent: blue

markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
    - toc:
          permalink: true
          title: On this page
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
