# Generated by Django 4.2.1 on 2023-09-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BftStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FY", "FY"),
                            ("QUARTER", "QUARTER"),
                            ("PERIOD", "PERIOD"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="Status",
                    ),
                ),
                ("value", models.CharField(max_length=30, verbose_name="Value")),
            ],
        ),
    ]
