# Generated by Django 5.0.6 on 2024-07-26 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bft", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BftUserFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("favorite_name", models.CharField(max_length=30)),
                ("favorite_link", models.CharField(max_length=125)),
                (
                    "bftuser",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Favorite",
                    ),
                ),
            ],
        ),
    ]
