# Generated by Django 5.0.6 on 2025-02-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bft", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capitalinyear",
            name="fy",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2021, "2021"),
                    (2022, "2022"),
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                    (2026, "2026"),
                    (2027, "2027"),
                    (2028, "2028"),
                ],
                default=2025,
                verbose_name="Fiscal Year",
            ),
        ),
        migrations.AlterField(
            model_name="capitalnewyear",
            name="fy",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2021, "2021"),
                    (2022, "2022"),
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                    (2026, "2026"),
                    (2027, "2027"),
                    (2028, "2028"),
                ],
                default=2025,
                verbose_name="Fiscal Year",
            ),
        ),
        migrations.AlterField(
            model_name="capitalyearend",
            name="fy",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2021, "2021"),
                    (2022, "2022"),
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                    (2026, "2026"),
                    (2027, "2027"),
                    (2028, "2028"),
                ],
                default=2025,
                verbose_name="Fiscal Year",
            ),
        ),
        migrations.AlterField(
            model_name="costcenterallocation",
            name="fy",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2021, "2021"),
                    (2022, "2022"),
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                    (2026, "2026"),
                    (2027, "2027"),
                    (2028, "2028"),
                ],
                default=2025,
                verbose_name="Fiscal Year",
            ),
        ),
        migrations.AlterField(
            model_name="fundcenterallocation",
            name="fy",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2021, "2021"),
                    (2022, "2022"),
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                    (2026, "2026"),
                    (2027, "2027"),
                    (2028, "2028"),
                ],
                default=2025,
                verbose_name="Fiscal Year",
            ),
        ),
    ]
