# Generated by Django 5.0.6 on 2024-07-31 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bft", "0002_bftuserfavorite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bftuserfavorite",
            name="bftuser",
        ),
        migrations.AddField(
            model_name="bftuserfavorite",
            name="owner",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner's Favorite",
            ),
        ),
    ]
