# Generated by Django 5.0.6 on 2024-07-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bft", "0003_remove_bftuserfavorite_bftuser_bftuserfavorite_owner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BftUserFavorite",
            new_name="Bookmark",
        ),
        migrations.RenameField(
            model_name="bookmark",
            old_name="favorite_link",
            new_name="bookmark_link",
        ),
        migrations.RenameField(
            model_name="bookmark",
            old_name="favorite_name",
            new_name="bookmark_name",
        ),
    ]
