# Generated by Django 5.0.6 on 2024-07-31 18:04

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bft", "0004_rename_bftuserfavorite_bookmark_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="bookmark",
            managers=[
                ("search", django.db.models.manager.Manager()),
            ],
        ),
    ]
