# Generated by Django 5.0.6 on 2024-08-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bft", "0005_alter_bookmark_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="bookmark_link",
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
