# Generated by Django 5.0.6 on 2024-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bft", "0007_alter_bookmark_managers_alter_bookmark_bookmark_link_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookmark",
            name="bft_bookmark_is_unique",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="bookmark_query_string",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                fields=("bookmark_link", "bookmark_query_string", "owner"), name="bft_bookmark_is_unique"
            ),
        ),
    ]
