# Generated by Django 5.0.6 on 2024-09-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bft", "0008_remove_bookmark_bft_bookmark_is_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundcenter",
            name="fundcenter",
            field=models.CharField(max_length=6, verbose_name="Fund Center"),
        ),
        migrations.AlterField(
            model_name="fundcenter",
            name="sequence",
            field=models.CharField(max_length=25, verbose_name="FC Path"),
        ),
        migrations.AddConstraint(
            model_name="fundcenter",
            constraint=models.UniqueConstraint(
                fields=("fundcenter", "fundcenter_parent"), name="bft_fundcenter_is_unique"
            ),
        ),
    ]
