# Generated by Django 5.0.6 on 2024-10-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bft", "0009_alter_fundcenter_fundcenter_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="costcenter",
            constraint=models.UniqueConstraint(
                fields=("costcenter", "costcenter_parent"), name="bft_costcenter_is_unique"
            ),
        ),
    ]
