# Generated by Django 5.0.6 on 2024-10-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bft", "0010_costcenter_bft_costcenter_is_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcenter",
            name="costcenter",
            field=models.CharField(max_length=6, verbose_name="Cost Center"),
        ),
    ]
