# Generated by Django 4.2.1 on 2024-02-22 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lineitems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineforecast",
            name="owner",
            field=models.ForeignKey(
                default="",
                limit_choices_to={"procurement_officer": True},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
