# Generated by Django 4.2.1 on 2023-06-06 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lineitems", "0002_lineitem_fcintegrity"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecastamount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("comment", models.CharField(blank=True, max_length=512, null=True)),
                ("deliverydate", models.DateField(blank=True, null=True)),
                ("delivered", models.BooleanField(default=False)),
                ("buyer", models.CharField(blank=True, max_length=175, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "status",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "lineitem",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fcst",
                        to="lineitems.lineitem",
                    ),
                ),
            ],
        ),
    ]
