# Generated by Django 4.2.1 on 2023-11-10 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lineitems", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineforecast",
            name="owner",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
