# Generated by Django 4.2.2 on 2023-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineitems", "0003_lineforecast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineforecast",
            name="deliverydate",
            field=models.DateField(blank=True, null=True, verbose_name="Delivery Date"),
        ),
    ]
