# Generated by Django 4.1.5 on 2023-11-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lineitems", "0005_lineforecast_balance_lineforecast_spent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lineforecast",
            old_name="balance",
            new_name="balance_initial",
        ),
        migrations.RenameField(
            model_name="lineforecast",
            old_name="spent",
            new_name="spent_initial",
        ),
        migrations.RenameField(
            model_name="lineforecast",
            old_name="workingplan",
            new_name="workingplan_initial",
        ),
    ]
