# Generated by Django 5.0.4 on 2024-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostCenterInYearEncumbrance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fund", models.CharField(max_length=4, verbose_name="Fund")),
                ("source", models.CharField(max_length=24, verbose_name="Source")),
                ("costcenter", models.CharField(max_length=6, verbose_name="Cost Center")),
                ("period", models.CharField(max_length=2, verbose_name="Period")),
                ("fy", models.CharField(max_length=4, verbose_name="FY")),
                (
                    "spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Spent"),
                ),
                (
                    "commitment",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Commitment"
                    ),
                ),
                (
                    "pre_commitment",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Pre Commitment"
                    ),
                ),
                (
                    "fund_reservation",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Fund Reservation"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Balance"),
                ),
                (
                    "working_plan",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Working Plan"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cost Center Monthly Encumbrance",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CostCenterMonthlyAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fund", models.CharField(max_length=4, verbose_name="Fund")),
                ("source", models.CharField(max_length=24, verbose_name="Source")),
                ("costcenter", models.CharField(max_length=6, verbose_name="Cost Center")),
                ("period", models.CharField(max_length=2, verbose_name="Period")),
                ("fy", models.CharField(max_length=4, verbose_name="FY")),
                (
                    "allocation",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Allocation"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cost Center Monthly Allocations",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CostCenterMonthlyEncumbrance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fund", models.CharField(max_length=4, verbose_name="Fund")),
                ("source", models.CharField(max_length=24, verbose_name="Source")),
                ("costcenter", models.CharField(max_length=6, verbose_name="Cost Center")),
                ("period", models.CharField(max_length=2, verbose_name="Period")),
                ("fy", models.CharField(max_length=4, verbose_name="FY")),
                (
                    "spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Spent"),
                ),
                (
                    "commitment",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Commitment"
                    ),
                ),
                (
                    "pre_commitment",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Pre Commitment"
                    ),
                ),
                (
                    "fund_reservation",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Fund Reservation"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Balance"),
                ),
                (
                    "working_plan",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Working Plan"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cost Center Monthly Encumbrance",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CostCenterMonthlyForecastAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fund", models.CharField(max_length=4, verbose_name="Fund")),
                ("source", models.CharField(max_length=24, verbose_name="Source")),
                ("costcenter", models.CharField(max_length=6, verbose_name="Cost Center")),
                ("period", models.CharField(max_length=2, verbose_name="Period")),
                ("fy", models.CharField(max_length=4, verbose_name="FY")),
                (
                    "forecast_adjustment",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Forecast Adjustment"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cost Center Monthly Forecast Adjustment",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CostCenterMonthlyLineItemForecast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fund", models.CharField(max_length=4, verbose_name="Fund")),
                ("source", models.CharField(max_length=24, verbose_name="Source")),
                ("costcenter", models.CharField(max_length=6, verbose_name="Cost Center")),
                ("period", models.CharField(max_length=2, verbose_name="Period")),
                ("fy", models.CharField(max_length=4, verbose_name="FY")),
                (
                    "line_item_forecast",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Line Item Forecast"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Line Item Monthly Forecast",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="costcenterinyearencumbrance",
            constraint=models.UniqueConstraint(
                fields=("fund", "source", "costcenter", "period", "fy"),
                name="reports_costcenterinyearencumbrance_is_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="costcentermonthlyallocation",
            constraint=models.UniqueConstraint(
                fields=("fund", "source", "costcenter", "period", "fy"),
                name="reports_costcentermonthlyallocation_is_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="costcentermonthlyencumbrance",
            constraint=models.UniqueConstraint(
                fields=("fund", "source", "costcenter", "period", "fy"),
                name="reports_costcentermonthlyencumbrance_is_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="costcentermonthlyforecastadjustment",
            constraint=models.UniqueConstraint(
                fields=("fund", "source", "costcenter", "period", "fy"),
                name="reports_costcentermonthlyforecastadjustment_is_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="costcentermonthlylineitemforecast",
            constraint=models.UniqueConstraint(
                fields=("fund", "source", "costcenter", "period", "fy"),
                name="reports_costcentermonthlylineitemforecast_is_unique",
            ),
        ),
    ]
