# Generated by Django 4.2.1 on 2023-08-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="costcentermonthly",
            name="unique_cost_center_monthly_row",
        ),
        migrations.AddConstraint(
            model_name="costcentermonthly",
            constraint=models.UniqueConstraint(
                fields=("fund", "source", "cost_center", "period", "fy"),
                name="unique_cost_center_monthly_row",
            ),
        ),
    ]
