# Generated by Django 5.0.4 on 2024-04-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="costcentermonthly",
            name="forecast_adjustment",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True, verbose_name="Forecast Adjustment"
            ),
        ),
    ]
