# Generated by Django 5.0.4 on 2024-05-02 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_costcentermonthly_forecast_adjustment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CostCenterMonthly",
        ),
    ]
