# Generated by Django 4.2.1 on 2023-08-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reports",
            "0002_remove_costcentermonthly_unique_cost_center_monthly_row_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="costcentermonthly",
            name="forecast_ajustment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
