# Generated by Django 5.0.4 on 2024-06-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_costcenterinyearencumbrance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InYearData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fund", models.CharField(max_length=4, verbose_name="Fund")),
                ("source", models.CharField(max_length=24, verbose_name="Source")),
                ("costcenter", models.CharField(max_length=6, verbose_name="Cost Center")),
                ("period", models.CharField(max_length=2, verbose_name="Period")),
                ("fy", models.CharField(max_length=4, verbose_name="FY")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="inyeardata",
            constraint=models.UniqueConstraint(
                fields=("fund", "source", "costcenter", "period", "fy"), name="reports_inyeardata_is_unique"
            ),
        ),
    ]
