# Generated by Django 4.1.5 on 2023-08-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_alter_costcentermonthly_allocation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="costcentermonthly",
            options={"verbose_name_plural": "Cost Center Monthly"},
        ),
        migrations.RemoveField(
            model_name="costcentermonthly",
            name="allocation",
        ),
        migrations.RemoveField(
            model_name="costcentermonthly",
            name="charges",
        ),
        migrations.RemoveField(
            model_name="costcentermonthly",
            name="forecast",
        ),
        migrations.RemoveField(
            model_name="costcentermonthly",
            name="forecast_ajustment",
        ),
    ]
