# Generated by Django 5.0.4 on 2024-05-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="costcentermonthly",
            constraint=models.UniqueConstraint(
                fields=("fund", "source", "costcenter", "period", "fy"), name="reports_costcentermonthly_is_unique"
            ),
        ),
    ]
