# Generated by Django 4.2.1 on 2023-09-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_alter_costcentermonthly_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcentermonthly",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Balance",
            ),
        ),
        migrations.AlterField(
            model_name="costcentermonthly",
            name="commitment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Commitment",
            ),
        ),
        migrations.AlterField(
            model_name="costcentermonthly",
            name="fund",
            field=models.CharField(max_length=4, verbose_name="Fund"),
        ),
        migrations.AlterField(
            model_name="costcentermonthly",
            name="fund_reservation",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Fund Reservation",
            ),
        ),
        migrations.AlterField(
            model_name="costcentermonthly",
            name="fy",
            field=models.CharField(max_length=4, verbose_name="FY"),
        ),
        migrations.AlterField(
            model_name="costcentermonthly",
            name="period",
            field=models.CharField(max_length=2, verbose_name="Period"),
        ),
        migrations.AlterField(
            model_name="costcentermonthly",
            name="pre_commitment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Pre Commitment",
            ),
        ),
        migrations.AlterField(
            model_name="costcentermonthly",
            name="source",
            field=models.CharField(max_length=24, verbose_name="Source"),
        ),
        migrations.AlterField(
            model_name="costcentermonthly",
            name="spent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Spent",
            ),
        ),
        migrations.AlterField(
            model_name="costcentermonthly",
            name="working_plan",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Working Plan",
            ),
        ),
    ]
