# Generated by Django 5.0.4 on 2024-05-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0005_costcentermonthly_reports_costcentermonthly_is_unique"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CostCenterMonthly",
            new_name="CostCenterMonthlyEncumbrance",
        ),
        migrations.RemoveConstraint(
            model_name="costcentermonthlyencumbrance",
            name="reports_costcentermonthly_is_unique",
        ),
        migrations.AddConstraint(
            model_name="costcentermonthlyencumbrance",
            constraint=models.UniqueConstraint(
                fields=("fund", "source", "costcenter", "period", "fy"),
                name="reports_costcentermonthlyencumbrance_is_unique",
            ),
        ),
    ]
