# Generated by Django 5.0.4 on 2024-05-02 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0006_rename_costcentermonthly_costcentermonthlyencumbrance_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="costcentermonthlyencumbrance",
            options={"verbose_name_plural": "Cost Center Monthly Encumbrance"},
        ),
    ]
