# Generated by Django 5.0.4 on 2024-05-09 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0010_costcentermonthlyallocation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costcentermonthlyencumbrance",
            name="forecast_adjustment",
        ),
    ]
