# Generated by Django 4.2.1 on 2023-11-30 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("encumbrance", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EncumbranceImport",
        ),
    ]
