# Generated by Django 4.2.1 on 2023-11-02 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "costcenter",
                    models.CharField(
                        max_length=6, unique=True, verbose_name="Cost Center"
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        blank=True,
                        max_length=35,
                        null=True,
                        verbose_name="Cost Center Name",
                    ),
                ),
                (
                    "isforecastable",
                    models.BooleanField(default=False, verbose_name="Is Forecastable"),
                ),
                (
                    "isupdatable",
                    models.BooleanField(default=False, verbose_name="Is Updatable"),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "sequence",
                    models.CharField(
                        default="", max_length=25, unique=True, verbose_name="CC Path"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cost Centers",
                "ordering": ["costcenter"],
            },
        ),
        migrations.CreateModel(
            name="CostCenterAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fy",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2019, "2019"),
                            (2020, "2020"),
                            (2021, "2021"),
                            (2022, "2022"),
                            (2023, "2023"),
                            (2024, "2024"),
                            (2025, "2025"),
                            (2026, "2026"),
                        ],
                        default=2023,
                        verbose_name="Fiscal Year",
                    ),
                ),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("0", "Q0"),
                            ("1", "Q1"),
                            ("2", "Q2"),
                            ("3", "Q3"),
                            ("4", "Q4"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Cost Center Allocations",
            },
        ),
        migrations.CreateModel(
            name="ForecastAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Forecast Adjustments",
                "ordering": ["costcenter", "fund"],
            },
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund", models.CharField(max_length=4, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("vote", models.CharField(max_length=1)),
                ("download", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Funds",
                "ordering": ["-download", "fund"],
            },
        ),
        migrations.CreateModel(
            name="FundCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fundcenter",
                    models.CharField(
                        max_length=6, unique=True, verbose_name="Fund Center"
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="Fund Center Name",
                    ),
                ),
                (
                    "sequence",
                    models.CharField(
                        max_length=25, unique=True, verbose_name="FC Path"
                    ),
                ),
                ("level", models.SmallIntegerField(default=0, verbose_name="Level")),
            ],
            options={
                "verbose_name_plural": "Fund Centers",
                "ordering": ["fundcenter"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=24, unique=True)),
            ],
            options={
                "verbose_name_plural": "Sources",
            },
        ),
        migrations.CreateModel(
            name="FundCenterAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fy",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2019, "2019"),
                            (2020, "2020"),
                            (2021, "2021"),
                            (2022, "2022"),
                            (2023, "2023"),
                            (2024, "2024"),
                            (2025, "2025"),
                            (2026, "2026"),
                        ],
                        default=2023,
                        verbose_name="Fiscal Year",
                    ),
                ),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("0", "Q0"),
                            ("1", "Q1"),
                            ("2", "Q2"),
                            ("3", "Q3"),
                            ("4", "Q4"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "fund",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="costcenter.fund",
                    ),
                ),
                (
                    "fundcenter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="costcenter.fundcenter",
                        verbose_name="Fund Center",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Fund Center Allocations",
            },
        ),
    ]
