# Generated by Django 4.2.1 on 2023-05-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund", models.CharField(max_length=4, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("vote", models.CharField(max_length=1)),
                ("download", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Funds",
                "ordering": ["-download", "fund"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=24)),
            ],
            options={
                "verbose_name_plural": "Sources",
            },
        ),
        migrations.CreateModel(
            name="FundCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fundcenter", models.CharField(max_length=6, unique=True)),
                ("shortname", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="parent_fc",
                        to="costcenter.fundcenter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("costcenter", models.CharField(max_length=6, unique=True)),
                ("shortname", models.CharField(blank=True, max_length=35, null=True)),
                ("isforecastable", models.BooleanField(default=False)),
                ("isupdatable", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "fund",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="costcenter.fund",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        default="0",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="children",
                        to="costcenter.fundcenter",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="costcenter.source",
                    ),
                ),
            ],
        ),
    ]
