# Generated by Django 4.2.1 on 2023-05-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fund", models.CharField(max_length=4, unique=True)),
                ("name", models.CharField(max_length=30)),
                ("vote", models.CharField(max_length=1)),
                ("download", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-download", "fund"],
            },
        ),
    ]
