# Generated by Django 4.2.1 on 2023-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costcenter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="fund",
            options={"ordering": ["-download", "fund"], "verbose_name_plural": "Funds"},
        ),
    ]
