# Generated by Django 4.2.1 on 2023-09-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="costcenterallocation",
            constraint=models.UniqueConstraint(
                fields=("fund", "costcenter", "quarter", "fy"),
                name="unique_cost_center_allocation",
            ),
        ),
    ]
