# Generated by Django 4.2.1 on 2023-11-01 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("costcenter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundcenterallocation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fundcenter",
            name="fundcenter_parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="parent_fc",
                to="costcenter.fundcenter",
                verbose_name="Fund Center Parent",
            ),
        ),
        migrations.AddField(
            model_name="forecastadjustment",
            name="costcenter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="costcenter.costcenter",
                verbose_name="Cost Center",
            ),
        ),
        migrations.AddField(
            model_name="forecastadjustment",
            name="fund",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="costcenter.fund",
            ),
        ),
        migrations.AddField(
            model_name="forecastadjustment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="costcenterallocation",
            name="costcenter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="costcenter.costcenter",
                verbose_name="Cost Center",
            ),
        ),
        migrations.AddField(
            model_name="costcenterallocation",
            name="fund",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="costcenter.fund",
            ),
        ),
        migrations.AddField(
            model_name="costcenterallocation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="costcenter_parent",
            field=models.ForeignKey(
                default="0",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="children",
                to="costcenter.fundcenter",
                verbose_name="Cost Center Parent",
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="fund",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                to="costcenter.fund",
                verbose_name="Fund",
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="source",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                to="costcenter.source",
                verbose_name="Source",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundcenterallocation",
            constraint=models.UniqueConstraint(
                fields=("fund", "fundcenter", "quarter", "fy"),
                name="unique_fund_center_allocation",
            ),
        ),
        migrations.AddConstraint(
            model_name="costcenterallocation",
            constraint=models.UniqueConstraint(
                fields=("fund", "costcenter", "quarter", "fy"),
                name="unique_cost_center_allocation",
            ),
        ),
    ]
