# Generated by Django 4.1.5 on 2024-02-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costcenter", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="capitalinyear",
            constraint=models.UniqueConstraint(
                fields=("fund", "capital_project", "commit_item", "fy"),
                name="costcenter_capitalinyear_is_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="capitalnewyear",
            constraint=models.UniqueConstraint(
                fields=("fund", "capital_project", "commit_item", "fy"),
                name="costcenter_capitalnewyear_is_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="capitalyearend",
            constraint=models.UniqueConstraint(
                fields=("fund", "capital_project", "commit_item", "fy"),
                name="costcenter_capitalyearend_is_unique",
            ),
        ),
    ]
