# Generated by Django 4.2.1 on 2023-05-11 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0002_forecastadjustment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forecastadjustment",
            options={
                "ordering": ["costcenter", "fund"],
                "verbose_name_plural": "Forecast Adjustments",
            },
        ),
    ]
