# Generated by Django 4.2.1 on 2023-09-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0002_costcenterallocation_unique_cost_center_allocation"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="fundcenterallocation",
            constraint=models.UniqueConstraint(
                fields=("fund", "fundcenter", "quarter", "fy"),
                name="unique_fund_center_allocation",
            ),
        ),
    ]
