# Generated by Django 4.2.1 on 2023-11-20 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("costcenter", "0003_costcenter_procurement_officer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcenter",
            name="procurement_officer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"procurement_officer": True},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
