# Generated by Django 4.1.5 on 2024-02-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "costcenter",
            "0003_capitalinyear_costcenter_capitalinyear_is_unique_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="capitalinyear",
            name="costcenter_capitalinyear_is_unique",
        ),
        migrations.AddConstraint(
            model_name="capitalinyear",
            constraint=models.UniqueConstraint(
                fields=("fund", "capital_project", "commit_item", "fy", "quarter"),
                name="capital_in_year_is_unique",
            ),
        ),
    ]
