# Generated by Django 4.2.1 on 2023-09-14 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0003_fundcenterallocation_unique_fund_center_allocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costcenter",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="fundcenter",
            name="parent",
        ),
        migrations.AddField(
            model_name="costcenter",
            name="costcenter_parent",
            field=models.ForeignKey(
                default="0",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="children",
                to="costcenter.fundcenter",
                verbose_name="Cost Center Parent",
            ),
        ),
        migrations.AddField(
            model_name="fundcenter",
            name="fundcenter_parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="parent_fc",
                to="costcenter.fundcenter",
                verbose_name="Fund Center Parent",
            ),
        ),
    ]
