# Generated by Django 4.2.1 on 2023-05-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0003_alter_forecastadjustment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source",
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
