# Generated by Django 4.2.1 on 2024-01-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0004_alter_costcenter_procurement_officer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcenterallocation",
            name="fy",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2020, "2020"),
                    (2021, "2021"),
                    (2022, "2022"),
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                    (2026, "2026"),
                    (2027, "2027"),
                ],
                default=2024,
                verbose_name="Fiscal Year",
            ),
        ),
        migrations.AlterField(
            model_name="fundcenterallocation",
            name="fy",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2020, "2020"),
                    (2021, "2021"),
                    (2022, "2022"),
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                    (2026, "2026"),
                    (2027, "2027"),
                ],
                default=2024,
                verbose_name="Fiscal Year",
            ),
        ),
    ]
