# Generated by Django 4.2.1 on 2023-10-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0005_alter_fundcenter_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcenter",
            name="sequence",
            field=models.CharField(
                default="", max_length=25, unique=True, verbose_name="CC Path"
            ),
        ),
        migrations.AlterField(
            model_name="fundcenter",
            name="sequence",
            field=models.CharField(max_length=25, unique=True, verbose_name="FC Path"),
        ),
    ]
