# Generated by Django 4.2.1 on 2024-02-07 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("costcenter", "0005_alter_costcenterallocation_fy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitalProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_no",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="Project No"
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        blank=True, max_length=35, verbose_name="Project Name"
                    ),
                ),
                (
                    "isupdatable",
                    models.BooleanField(default=False, verbose_name="Is Updatable"),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "sequence",
                    models.CharField(
                        default="", max_length=25, unique=True, verbose_name="CC Path"
                    ),
                ),
                (
                    "fundcenter",
                    models.ForeignKey(
                        default="0",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="capital_projects",
                        to="costcenter.fundcenter",
                        verbose_name="Fund Center",
                    ),
                ),
                (
                    "procurement_officer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"procurement_officer": True},
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Capital Projects",
                "ordering": ["project_no"],
            },
        ),
        migrations.CreateModel(
            name="CapitalForecasting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fy",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2020, "2020"),
                            (2021, "2021"),
                            (2022, "2022"),
                            (2023, "2023"),
                            (2024, "2024"),
                            (2025, "2025"),
                            (2026, "2026"),
                            (2027, "2027"),
                        ],
                        default=2024,
                        verbose_name="Fiscal Year",
                    ),
                ),
                ("commit_item", models.PositiveSmallIntegerField(default=0)),
                ("initial_allocation", models.PositiveIntegerField(default=0)),
                ("q1_allocation", models.PositiveIntegerField(default=0)),
                ("q2_allocation", models.PositiveIntegerField(default=0)),
                ("q3_allocation", models.PositiveIntegerField(default=0)),
                ("q4_allocation", models.PositiveIntegerField(default=0)),
                ("q1_forecast", models.PositiveIntegerField(default=0)),
                ("q2_forecast", models.PositiveIntegerField(default=0)),
                ("q3_forecast", models.PositiveIntegerField(default=0)),
                ("q4_forecast", models.PositiveIntegerField(default=0)),
                ("q1_le", models.PositiveIntegerField(default=0)),
                ("q2_le", models.PositiveIntegerField(default=0)),
                ("q3_le", models.PositiveIntegerField(default=0)),
                ("q4_le", models.PositiveIntegerField(default=0)),
                ("q1_he", models.PositiveIntegerField(default=0)),
                ("q2_he", models.PositiveIntegerField(default=0)),
                ("q3_he", models.PositiveIntegerField(default=0)),
                ("q4_he", models.PositiveIntegerField(default=0)),
                ("q1_spent", models.PositiveIntegerField(default=0)),
                ("q2_spent", models.PositiveIntegerField(default=0)),
                ("q3_spent", models.PositiveIntegerField(default=0)),
                ("q4_spent", models.PositiveIntegerField(default=0)),
                ("q1_co", models.PositiveIntegerField(default=0)),
                ("q2_co", models.PositiveIntegerField(default=0)),
                ("q3_co", models.PositiveIntegerField(default=0)),
                ("q4_co", models.PositiveIntegerField(default=0)),
                ("q1_pc", models.PositiveIntegerField(default=0)),
                ("q2_pc", models.PositiveIntegerField(default=0)),
                ("q3_pc", models.PositiveIntegerField(default=0)),
                ("q4_pc", models.PositiveIntegerField(default=0)),
                ("q1_fr", models.PositiveIntegerField(default=0)),
                ("q2_fr", models.PositiveIntegerField(default=0)),
                ("q3_fr", models.PositiveIntegerField(default=0)),
                ("q4_fr", models.PositiveIntegerField(default=0)),
                ("ye_spent", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField()),
                (
                    "capital_project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="costcenter.capitalproject",
                        verbose_name="Capital Project",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="costcenter.fund",
                    ),
                ),
            ],
        ),
    ]
