# Generated by Django 4.2.1 on 2023-05-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costcenter", "0005_alter_fundcenter_options_alter_fundcenter_fundcenter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundcenter",
            name="fundcenter",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
