# Generated by Django 4.2.1 on 2024-02-07 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0006_capitalproject_capitalforecasting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capitalproject",
            name="sequence",
        ),
    ]
