# Generated by Django 4.2.2 on 2023-06-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("costcenter", "0008_allocation_costcenterallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundcenter",
            name="sequence",
            field=models.CharField(
                default=None, max_length=25, verbose_name="Sequence No"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="allocation",
            name="fy",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2019, "2019"),
                    (2020, "2020"),
                    (2021, "2021"),
                    (2022, "2022"),
                    (2023, "2023"),
                    (2024, "2024"),
                    (2025, "2025"),
                    (2026, "2026"),
                ],
                default=2023,
                verbose_name="Fiscal Year",
            ),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="costcenter",
            field=models.CharField(
                max_length=6, unique=True, verbose_name="Cost Center"
            ),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="isforecastable",
            field=models.BooleanField(default=False, verbose_name="Is Forecastable"),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="isupdatable",
            field=models.BooleanField(default=False, verbose_name="Is Updatable"),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="shortname",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="Short Name"
            ),
        ),
        migrations.AlterField(
            model_name="costcenterallocation",
            name="costcenter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="costcenter.costcenter",
                verbose_name="Cost Center",
            ),
        ),
        migrations.AlterField(
            model_name="forecastadjustment",
            name="costcenter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="costcenter.costcenter",
                verbose_name="Cost Center",
            ),
        ),
        migrations.AlterField(
            model_name="fundcenter",
            name="fundcenter",
            field=models.CharField(
                max_length=6, unique=True, verbose_name="Fund Center"
            ),
        ),
        migrations.AlterField(
            model_name="fundcenter",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="parent_fc",
                to="costcenter.fundcenter",
            ),
        ),
        migrations.AlterField(
            model_name="fundcenter",
            name="shortname",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Short Name"
            ),
        ),
    ]
