# Generated by Django 4.2.2 on 2023-06-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costcenter", "0009_fundcenter_sequence_alter_allocation_fy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundcenter",
            name="sequence",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Sequence No"
            ),
        ),
    ]
