# Generated by Django 4.2.2 on 2023-07-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0011_alter_fundcenter_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundcenter",
            name="sequence",
            field=models.CharField(
                max_length=25, null=True, verbose_name="Sequence No"
            ),
        ),
    ]
