# Generated by Django 4.1.5 on 2023-07-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costcenter", "0012_alter_fundcenter_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundcenter",
            name="sequence",
            field=models.CharField(
                max_length=25, null=True, unique=True, verbose_name="Sequence No"
            ),
        ),
    ]
