# Generated by Django 4.2.1 on 2023-07-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0015_alter_fundcenter_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundcenter",
            name="sequence",
            field=models.CharField(
                default="1", max_length=25, unique=True, verbose_name="Sequence No"
            ),
        ),
    ]
