# Generated by Django 4.2.1 on 2023-08-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0016_alter_fundcenter_sequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundCenterAllocation",
            fields=[
                (
                    "allocation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="costcenter.allocation",
                    ),
                ),
                (
                    "fundcenter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="costcenter.fundcenter",
                        verbose_name="Fund Center",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Fund Center Allocations",
            },
            bases=("costcenter.allocation",),
        ),
    ]
