# Generated by Django 4.2.1 on 2023-08-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0018_costcenter_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcenter",
            name="sequence",
            field=models.CharField(
                default="", max_length=25, verbose_name="Sequence No"
            ),
        ),
    ]
