# Generated by Django 4.2.1 on 2023-09-05 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0021_alter_allocation_quarter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocation",
            name="quarter",
            field=models.CharField(
                choices=[
                    ("0", "Q0"),
                    ("1", "Q1"),
                    ("2", "Q2"),
                    ("3", "Q3"),
                    ("4", "Q4"),
                ],
                default="0",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="fund",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                to="costcenter.fund",
                verbose_name="Fund",
            ),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="parent",
            field=models.ForeignKey(
                default="0",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="children",
                to="costcenter.fundcenter",
                verbose_name="Parent",
            ),
        ),
        migrations.AlterField(
            model_name="costcenter",
            name="source",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                to="costcenter.source",
                verbose_name="Source",
            ),
        ),
    ]
