# Generated by Django 4.2.1 on 2023-09-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("costcenter", "0022_alter_allocation_quarter_alter_costcenter_fund_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costcenter",
            name="shortname",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="Cost Center Name"
            ),
        ),
        migrations.AlterField(
            model_name="fundcenter",
            name="shortname",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Fund Center Name"
            ),
        ),
    ]
